import {
    ArrowLeft,
    ArrowRight,
    Award,
    Bike,
    Bolt,
    Box,
    BriefcaseBusiness,
    Calendar,
    Check,
    ChevronDown,
    Clock,
    CreditCard,
    Eye,
    EyeOff,
    Globe,
    Heart,
    House,
    Lock,
    LockOpen,
    LogOut,
    LucideIcons,
    Mail,
    MapPin,
    MapPinPlus,
    MapPinned,
    Phone,
    Plus,
    QrCode,
    ReceiptText,
    ScanQrCode,
    Settings,
    Shield,
    ShoppingBag,
    Star,
    Trash2,
    TriangleAlert,
    Truck,
    UserRound,
    X,
    Layers,
    Sparkles,
    BrainCircuit,
    Brain
} from 'lucide-angular';

export const lucideIconAliases: LucideIcons = {
    ArrowBottom: ChevronDown,
    ArrowLeft,
    ArrowRight,
    Award,
    Bag: ShoppingBag,
    Bolt,
    Box,
    Briefcase: BriefcaseBusiness,
    Calendar,
    Card: CreditCard,
    Check,
    CicloMotor: Bike,
    Clock,
    Close: X,
    CreditCard,
    Delete: Trash2,
    Email: Mail,
    Exclamation: TriangleAlert,
    Eye,
    EyeOff,
    GoogleIcon: Globe,
    Heart,
    Home: House,
    Location: MapPin,
    LocationAdd: MapPinPlus,
    Lock,
    LockOpen,
    Logout: LogOut,
    Person: UserRound,
    Phone,
    PinDrop: MapPinned,
    Pix: ScanQrCode,
    Plus,
    QrCode,
    ReceiptLong: ReceiptText,
    Settings,
    Shield,
    Star,
    Trash: Trash2,
    Truck,
    User: UserRound,
    Warning: TriangleAlert,
    WorksSpace: Award,
    layers: Layers,
    sparkles: Sparkles,
    brainCircuit: BrainCircuit,
    brain: Brain
};
